# Generated by Django 5.1.1 on 2024-11-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdhospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='nombre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
